# Generated by Django 3.2.5 on 2022-04-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group_name',
            field=models.ForeignKey(default='no_group', on_delete=django.db.models.deletion.SET_DEFAULT, to='notes.notesgroups', verbose_name='Группа'),
        ),
    ]
