# Generated by Django 3.2.5 on 2022-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_create',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата создания'),
        ),
    ]
