# Generated by Django 4.0.3 on 2022-04-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('notes', '0002_alter_notes_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='groups.notesgroups', verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='NotesGroups',
        ),
    ]
