# Generated by Django 4.0.3 on 2022-07-28 17:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_notesgroups_group_owner'),
        ('notes', '0003_alter_notes_group_name_delete_notesgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='groups.notesgroups', verbose_name='Группа'),
        ),
    ]
