# Generated by Django 3.2.5 on 2022-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20220330_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesgroups',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
