# Generated by Django 4.0.4 on 2022-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_important_alter_notes_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важно'),
        ),
    ]
